### ISSUE TITLE
footerData creading Horizontal scroll bar 

### ISSUE THREAD

**Issue by hemant17** [priyam-raj/playlist-data#2]
After fetch the playlist-meta section has static padding which creating vertical scroll bar 
![image](https://user-images.githubusercontent.com/10548023/199185029-6775cbbb-190b-45d1-819e-fdb597edb6c0.png)

**Comment by hemant17** [comment]
#3 Raised PR for this

**Comment by priyam-raj** [comment]
Thanks for your contribution @hemant17!
